### ISSUE TITLE
Generation Overlaps

### ISSUE THREAD

**Issue by spidersouris** [TC-Zheng/ActuosusAI#21]
Currently, there are several actions that can make text generations overlap:
- After clicking on a token in the token possibility list to force a new generation, clicking on that same token then on "Previous" during streaming will produce an overlap with the previous generation.
- Clicking "Clear All" during streaming will clear what has been generated so far but the generation will continue.

It doesn't seem there is an official implementation of `cancel()` in llama-cpp-python yet but there is a PR for that: https://github.com/abetlen/llama-cpp-python/pull/733 — perhaps it could help?

**Comment by TC-Zheng** [comment]
I should be able to implement a cancelation mechanism since I am not actually streaming via llama-cpp-python, I wrote my own for loop and generates tokens one at a time.

I think I will only allow the user to clear or stop the generation explicitly and disable all other action during streaming to avoid confusion.

I will try to implement this. Thanks for the feedback.
